{
  "po_head_ex": {
    "pO_DATE": "2026-04-14T09:19:52.651Z",
    "pO_NO": "string",
    "povaliD_DATE": "2026-04-14T09:19:52.651Z",
    "venD_CODE": "stri",
    "quoT_NO": "string",
    "quoT_DATE": "2026-04-14T09:19:52.651Z",
    "proJ_CODE": "str",
    "basiC_AMT": 0,
    "disC_PERCENT": 0,
    "pacK_FWD_AMT": 0,
    "pacK_FWD_PERCENT": 0,
    "transporT_AMT": 0,
    "octroI_FLAG": "s",
    "currency": "strin",
    "pO_CATG": "st",
    "prinT_FLAG": "s",
    "advancE_AMT": 0,
    "modvaT_FLAG": "s",
    "openpO_FLAG": "s",
    "toT_DISCAMT": 0,
    "amenD_NO": "st",
    "transporT_FLAG": "s",
    "toT_STAX": 0,
    "toT_EXCISE": 0,
    "toT_OTAX": 0,
    "profceN_CD": "str",
    "depT_CODE": "str",
    "bal_amt": 0,
    "remark": "string",
    "advancE_AMT_PAID": 0,
    "trans_unit": "str",
    "delv_days": 0,
    "delv_period": "string",
    "po_type": "s",
    "delivery_location": "string",
    "transportername": "string",
    "user_name": "string",
    "amend_date": "2026-04-14T09:19:52.651Z",
    "pack_fwd_flag": "s",
    "schedule_flag": "s",
    "approved_by": "string",
    "approval_date": "2026-04-14T09:19:52.651Z",
    "approval_flag": "s",
    "inS_flag": "s",
    "inS_per": 0,
    "inS_amt": 0,
    "buyer": "string",
    "trans_remark": "string",
    "other_PayCond": "string",
    "int_remark": "string",
    "conv_rate": 0,
    "mode_of_Dispatch": "string",
    "other_Charges": 0,
    "delv_term": "string",
    "delivery_date": "2026-04-14T09:19:52.651Z",
    "delivery_remark": "string",
    "load_amt": 0,
    "load_unit": "strin",
    "netVal": 0,
    "service_Amt": 0,
    "pack_unit": "strin",
    "schemeName": "string",
    "user_date": "2026-04-14T09:19:52.651Z",
    "postart_letter": "s",
    "holdLevel": "s",
    "app_date1": "2026-04-14T09:19:52.651Z",
    "app_by1": "string",
    "app_date2": "2026-04-14T09:19:52.651Z",
    "app_by2": "string",
    "org_disc_Percent": 0,
    "obasic_amt": 0,
    "sgstAmt": 0,
    "cgstAmt": 0,
    "igstAmt": 0,
    "grn_Trans_Amt": 0,
    "project_val": 0,
    "po_subcatg": "str",
    "grn_load_amt": 0
  },
  "list_Po_det_ex": [
    {
      "pO_DATE": "2",
      "iteM_CODE": "s",
      "rate": "s",
      "qty": 0,
      "disC_PERCENT": 0,
      "accepT_QTY": 0,
      "reJ_QTY": 0,
      "schedulE_FLAG": "s",
      "modvaT_FLAG": "s",
      "pO_NO": "string",
      "uom": "str",
      "cP_FLAG": "s",
      "indenT_FLAG": "s",
      "remark": "string",
      "op_code": "string",
      "packing_details": "string",
      "profceN_CD": "str",
      "weF_DATE": "2026-04-14T09:19:52.651Z",
      "amend_reason": "string",
      "amend_nos": "string",
      "send_date": "2026-04-14T09:19:52.651Z",
      "head_amend_nos": "str",
      "temp_receipt": "string",
      "org_amt": "string",
      "org_rate": "string",
      "org_Qty": "string",
      "org_disc": "string",
      "delivery_dt": "2026-04-14T09:19:52.651Z",
      "exc_rate": 0,
      "amort_rate": 0,
      "scheme_name": "string",
      "licence_no": "string",
      "file_no": "string",
      "licence_date": "2026-04-14T09:19:52.651Z",
      "bond_date": "2026-04-14T09:19:52.651Z",
      "sr_no": 0,
      "scheme_qty": 0,
      "amend_Res": "string",
      "child_code": "string",
      "tariff_Cd": "string",
      "wono": "string",
      "sgsTdetAmt": 0,
      "cgsTdetAmt": 0,
      "igsTdetAmt": 0,
      "sgsT_Cd": "str",
      "cgsT_Cd": "str",
      "igsT_Cd": "str",
      "tcs_cd": "str",
      "tcsAmt": 0
    }
  ],
  "list_Po_tax_ex": [
    {
      "pO_NO": "string",
      "pO_DATE": "2026-04-14T09:19:52.651Z",
      "taX_CODE": "str",
      "taX_AMT": 0,
      "profceN_CD": "str",
      "wef_Dt": "2026-04-14T09:19:52.651Z"
    }
  ],
  "list_Po_paycond_ex": [
    {
      "pO_NO": "string",
      "pO_DATE": "2026-04-14T09:19:52.651Z",
      "pC_CODE": 0,
      "percent": 0,
      "mode": "s",
      "period": 0,
      "dmflag": "s",
      "profceN_CD": "str",
      "sR_NO": 0
    }
  ],
  "list_Po_indent_ex": [
    {
      "pO_NO": "string",
      "pO_DATE": "2026-04-14T09:19:52.651Z",
      "inD_NO": "string",
      "inD_DATE": "2026-04-14T09:19:52.651Z",
      "iteM_CODE": "string",
      "qty": 0,
      "amenD_NO": "string",
      "profcen_cd": "str",
      "po_uom": "strin",
      "indent_uom": "strin"
    }
  ],
  "list_po_operation_Det_ex": [
    {
      "pO_NO": "string",
      "pO_DATE": "2026-04-14T09:19:52.651Z",
      "iteM_CODE": "string",
      "op_code": "string",
      "profceN_CD": "str",
      "rate": 0,
      "sr_no": 0,
      "main_op_code": "string"
    }
  ],
  "period": "string",
  "mM_DOC_DOCUMNET": "string",
  "mM_DOC_TYPE": "string",
  "profceN_CD": "string"
}